spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo
    username: admin
    password: admin
  mail:
    host: smtp.gmail.com
    username: neilge.edu@gmail.com
    password: Gxy660909
    protocol: smtp
    from: neilge.edu@gmail.com
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          starttls:
            enable: true
            requried: true
          ssl:
            enable: true
encoding:
  aes:
    key-seed: ajlkdfla
    algorithm: AES
    random-algorithm: SHA1PRNG
    transformation: AES/ECB/PKCS5Padding
    key-size: 128
    encode: utf-8

captcha:
  expire: 60

authorization:
  jwt:
    secret: abcdefg1234567
    expire: 3600000
  interceptor:
    blacklist:
      - /account/**
      - /course/**
    whitelist:
      - /account/captcha
      - /account/registration
      - /account/login
      - /course/courses

